server:
    port: 80

mybatis:
  type-aliases-package: com.yang.tucao.entity
spring:
  aop:
    proxy-target-class: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tucao?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

